apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-rhq8
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/somahesh-tenant/my-app/devfile-sample-python-basic-rhq8@sha256:c2aed63c08cf4b1ffa885aff7df9a6754c261a55b45fb5f773ed1a48c2fd924a
        name: my-python
        resources: {}
status: {}
